### ISSUE TITLE
Poor Documentation

### ISSUE THREAD

**Issue by RafDevX** [rafaelsgirao/ngramatical-bot#1] opened 2021-09-19 13:44 UTC
The `README.md` file does not explain how to run the bot; please fix.

**Comment by rafaelsgirao** [comment] 2021-09-24 07:11
Thanks for reporting this!
We have tracked down the cause of this issue and it will be fixed on the next release of the bot (though we don't have an ETA on this).

**Comment by rafaelsgirao** [comment] 2021-10-03 09:55
Closing due to inactivity.

**Closed by rafaelsgirao** 2021-10-03 09:55 UTC
Labels: bug
